### ISSUE TITLE
In model_search failure if setting the trials_save_file arg (~ln 486)

### ISSUE THREAD

**Issue by SteveOv** [SteveOv/ebop_maven#28]
If I try:
```Python
    best = fmin(fn = train_and_test_model,
                space = trials_pspace,
                trials = trials,
                algo = tpe.suggest,
                max_evals = MAX_HYPEROPT_EVALS,
                loss_threshold = HYPEROPT_LOSS_TH,
                catch_eval_exceptions = True,
                rstate=np.random.default_rng(SEED),
                trials_save_file=f"{results_dir}/trials.pkl",
                verbose=True,
                show_progressbar=False)
```

I get the following error:
```
Traceback (most recent call last):
  File "/home/steveo/projects/main/ebop_maven/model_search.py", line 478, in <module>
    best = fmin(fn = train_and_test_model,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steveo/anaconda3/envs/ebop_maven/lib/python3.12/site-packages/hyperopt/fmin.py", line 540, in fmin
    return trials.fmin(
           ^^^^^^^^^^^^
  File "/home/steveo/anaconda3/envs/ebop_maven/lib/python3.12/site-packages/hyperopt/base.py", line 671, in fmin
    return fmin(
           ^^^^^
  File "/home/steveo/anaconda3/envs/ebop_maven/lib/python3.12/site-packages/hyperopt/fmin.py", line 586, in fmin
    rval.exhaust()
  File "/home/steveo/anaconda3/envs/ebop_maven/lib/python3.12/site-packages/hyperopt/fmin.py", line 364, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "/home/steveo/anaconda3/envs/ebop_maven/lib/python3.12/site-packages/hyperopt/fmin.py", line 304, in run
    pickler.dump(self.trials, open(self.trials_save_file, "wb"))
  File "/home/steveo/anaconda3/envs/ebop_maven/lib/python3.12/site-packages/cloudpickle/cloudpickle.py", line 1461, in dump
    Pickler(file, protocol=protocol, buffer_callback=buffer_callback).dump(obj)
  File "/home/steveo/anaconda3/envs/ebop_maven/lib/python3.12/site-packages/cloudpickle/cloudpickle.py", line 1245, in dump
    return super().dump(obj)
           ^^^^^^^^^^^^^^^^^
TypeError: cannot pickle 'FuncGraph' object
```

**Comment by SteveOv** [comment]
It looks like it cannot pickly the model. I don't need to save the model this way, so I'll see if I can remove it.

**Comment by SteveOv** [comment]
Yup; the error does not occur if a do not store the model in the results dict, so changing lines 608-609 from
```Python
    return { "loss": mae, "status": status, "mae": mae, "mse": mse,
            "weighted_loss": weighted_loss, "AIC": aic, "BIC": bic, "model": candidate, "history": history }
```
to 
```Python
    return { "loss": mae, "status": status, "mae": mae, "mse": mse,
            "weighted_loss": weighted_loss, "AIC": aic, "BIC": bic, "history": history }
```

**Comment by SteveOv** [comment]
So, what I could do is write the candidate.summary() to the results dict. I just need enough information to recreate the best model; the model summary and model params json should be enough.

**Comment by SteveOv** [comment]
OK, I'm closing this now as I know what the problem is and I've created the issue #70 to cover the rework.
