### ISSUE TITLE
investigate revised strategy for training/validation dataset

### ISSUE THREAD

**Issue by SteveOv** [SteveOv/ebop_maven#7]
Currently I have training/validation/testing data split in advance by supplying valid_ratio and test_ratio params when calling datasets.make_dataset_files(). Another option would be to leave these ratios a zero, thenlet TF do the training/validation split on the fly and use the MIST dataset as the test dataset.  Final testing would be with the formal-test-dataset as it is now. This would make life simpler but I need to see how it would work out.

**Comment by SteveOv** [comment]
Looks like fit's validation_ratio argument won't work with the dataset pipelines I am using.

```
Traceback (most recent call last):
  File "/home/steveo/projects/main/ebop_maven/make_trained_cnn_model.py", line 189, in <module>
    history = model.fit(x = datasets[0],    # pylint: disable=invalid-name
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steveo/anaconda3/envs/ebop_maven/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/steveo/anaconda3/envs/ebop_maven/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler
    return fn(*args, **kwargs)
                  ^^^^^^^^^^^^^
TypeError: TensorFlowTrainer.fit() got an unexpected keyword argument 'validation_ratio'
```

**Comment by SteveOv** [comment]
Not much more to add. I'll continue to use make_datasets to split training and validation datasets in advance.

I have tested using the synthetic-mist-tess-dataset as the test dataset. It works, but interesting gives lower loss than the usual 10k rows from formal-training-dataset. I probably need to set this mist dataset up with better coverage if I'm to use it for testing.
